repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: main
    hooks:
      - id: ruff
        args: [
          "check",
          "--select=E,F,W,B,B9",
          "--extend-ignore=E501",
          ".",
        ]
